### PR TITLE
changed file names

### PR DESCRIPTION
**Pull request by annettegessner**
Tabea asked me to change a bunch of file names, since her Windows couldn't handle file names with special characters. 
As far as I know, Matt named the splitted files after volume, number in volume and added first letters of the first title he found, e.g.: PL9_0_EDIT.xml. I can only guess, that when there was no title to be found, the file name included some blank spaces, which I deleted as well as special characters as "*" and "/".
Here is  a list provided by Tabea including the file names I have changed:
PL10_8, 
PL17_21, 
PL21_4, 
PL27_0, 
PL27_1, 
PL29_42, 
PL29_4, 
PL29_9, 
PL30_0, 
PL35_11, 
PL37_0, 
PL40_47, 
PL48_3, 
PL50_2, 
PL60_3, 
PL62_13, 
PL63_2, 
PL67_22, 
PL67_42, 
PL72_14, 
PL72_39, 
PL77_9, 
PL84_1 and 
PL9_13.
@all: Please check, if you have been working with these files and if it affects your work!
@planatheisa: I changed all file names except PL67_22 and PL67_42, where I couldn't see anything wrong with the file name. Please check!
@Matt: You cool with this? Maybe you could change something about your script before the next split. Thanks!

### CODE REVIEW

**Comment by sonofmun** [comment]
What are the characters that were causing the problems? There should not 
have been any blank spaces but, if there were, I will take a look at my 
script and correct it.

On 04.04.2016 14:55, annettegessner wrote:
>
> Tabea asked me to change a bunch of file names, since her Windows 
> couldn't handle file names with special characters.
> As far as I know, Matt named the splitted files after volume, number 
> in volume and added first letters of the first title he found, e.g.: 
> PL9_0_EDIT.xml. I can only guess, that when there was no title to be 
> found, the file name included some blank spaces, which I deleted as 
> well as special characters as "*" and "/".
> Here is a list provided by Tabea including the file names I have changed:
> PL10_8,
> PL17_21,
> PL21_4,
> PL27_0,
> PL27_1,
> PL29_42,
> PL29_4,
> PL29_9,
> PL30_0,
> PL35_11,
> PL37_0,
> PL40_47,
> PL48_3,
> PL50_2,
> PL60_3,
> PL62_13,
> PL63_2,
> PL67_22,
> PL67_42,
> PL72_14,
> PL72_39,
> PL77_9,
> PL84_1 and
> PL9_13.
> @all <https://github.com/all>: Please check, if you have been working 
> with these files and if it affects your work!
> @planatheisa <https://github.com/planatheisa>: I changed all file 
> names except PL67_22 and PL67_42, where I couldn't see anything wrong 
> with the file name. Please check!
> @Matt <https://github.com/Matt>: You cool with this? Maybe you could 
> change something about your script before the next split. Thanks!
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105
>
>
>         Commit Summary
>
>   * changed file names
>
>
>         File Changes
>
>   * *R* split/PL10/PL10_8_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-0>
>     (0)
>   * *R* split/PL17/PL17_21_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-1>
>     (0)
>   * *R* split/PL21/PL21_4_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-2>
>     (0)
>   * *R* split/PL27/PL27_0_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-3>
>     (0)
>   * *R* split/PL27/PL27_1_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-4>
>     (0)
>   * *R* split/PL29/PL29_42_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-5>
>     (0)
>   * *R* split/PL29/PL29_4_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-6>
>     (0)
>   * *R* split/PL29/PL29_9_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-7>
>     (0)
>   * *R* split/PL30/PL30_0_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-8>
>     (0)
>   * *R* split/PL35/PL35_11_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-9>
>     (0)
>   * *R* split/PL37/PL37_0_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-10>
>     (0)
>   * *R* split/PL40/PL40_47_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-11>
>     (0)
>   * *R* split/PL48/PL48_3_I.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-12>
>     (0)
>   * *R* split/PL50/PL50_2_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-13>
>     (0)
>   * *R* split/PL60/PL60_3_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-14>
>     (0)
>   * *R* split/PL62/PL62_13_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-15>
>     (0)
>   * *R* split/PL63/PL63_2_E.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-16>
>     (0)
>   * *R* split/PL67/PL67_22_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-17>
>     (0)
>   * *R* split/PL67/PL67_42_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-18>
>     (0)
>   * *R* split/PL72/PL72_14_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-19>
>     (0)
>   * *R* split/PL72/PL72_39_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-20>
>     (0)
>   * *R* split/PL77/PL77_9_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-21>
>     (0)
>   * *R* split/PL84/PL84_1_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-22>
>     (0)
>   * *R* split/PL9/PL9_13_.xml
>     <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105/files#diff-23>
>     (0)
>
>
>         Patch Links:
>
>   * https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105.patch
>   * https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenGreekAndLatin/patrologia_latina-dev/pull/105>
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by annettegessner** [comment]
In most cases I changed something like 

PL30_0_
		.xml (one space, two tab)
into
PL30_0_.xml

the other cases were "*" and "\", but also there was a space, which could have caused the error.

**Comment by planatheisa** [comment]
PL67_22 has a "*" and _42 a some whitespace in the filename.

**Comment by planatheisa** [comment]
Can I merge the request, so I can find out if it works now?

**Comment by annettegessner** [comment]
I had hoped, @sonofmun would do that. O:-)

**Comment by annettegessner** [comment]
Merging my own pull request against protocol now. I am sooo evil!

**Comment by planatheisa** [comment]
It's working now. Thanks.

**Pull request merged**
