### PR TITLE
First attempt for making PL_3_4 CTS compliant

### PR DESCRIPTION
**Pull request by pmsprenger**
Discuss what's working and/or what's not working.
The author URN stoa0100a seems not to be in the Perseus Catalog. Stoa0100 does exist however. Not sure what to do about this.

### CODE REVIEW

**Comment by annettegessner** [comment]
@PonteIneptique Is the xPath ok like this, or should we get rid of the subtype?

**Comment by PonteIneptique** [comment]
If subtype is not necessary, then it should not be used :)

**Comment by annettegessner** [comment]
So, when do we consider it necessary? ;-) Never?

**Comment by PonteIneptique** [comment]
Necessary means that if you remove it, it breaks. ie. you have div at the same level with `@n` and you need to distinguish them :) It does not seem to be the case here.

**Comment by annettegessner** [comment]
So hook will show us, if it breaks? 
This would mean: In doubt leave subtype out and only insert, if hook tells you to.

**Comment by PonteIneptique** [comment]
Nope: Hook won't tell you if there is an issue, because it's not its role (it can't tell you if the passage in English is meant to be here neither should it). XPath needs to be checked by human and people need to see if there text is working well themselves. XPath also needs to be the simplest and shortest because adding any parameter actually represents a huge cost.

As a footnote, subtype can be useful if for the same xpath nodes can conflicts (ie you have `p[@n="1" and @subtype="foo"]` and `p[@n="1" and @subtype="bar"]` but you want only foo). As far as I know, this should not happen a lot as we are dealing with text we formatted ourselves.

**Comment by annettegessner** [comment]
Thanks a lot, Thibault! Let's see, if I got this: 
So if we make sure, that every div-tag's subtype on one level is always the same (e.g. "section", "chapter", ... etc.) and the only difference will be in the n-element (e.g. "1", "2", "preface", "letter", ... etc.), it should be possible to always leave he subtype in the xpath out.
As far as I remember, we already did that with CSEL, so it should hopefully not be a problem.
@pmsprenger  and @planatheisa: Please let me know, if this was understandable and if you encounter a case, where the subtype has to change on one ad the same level! If not, you don't have to (and should not) add "subtype" to the xPath - yay!

**Comment by PonteIneptique** [comment]
Close but no. What you need to ensure is that the only divs with `@n` at the level you are looking are divs you want to get. If they are not, then you should introduce a difference in the form of `subtype` selection.

**Comment by annettegessner** [comment]
As far as I know, ALL div-tags should contain an n-element and I guess, we want all those div-tags and textparts contained to appear as means to navigate in the text in the end (i.e. we want to "get" them). Sorry, it never occurred to me, that there might be textparts, that we don't want to "get". 
Did I "get" what you mean now? ;-) 
*headexploded*

**Comment by PonteIneptique** [comment]
Yup. You got it.

(example of when you want to use subtype is bad xml or mixed content, such as one xml with translation and edition )

**Comment by annettegessner** [comment]
Hooray!
So @pmsprenger and @planatheisa: As far as I know, there should be NO case, where we need to include the subtype in the xPath. This means less work for you two, just make sure the number of levels is accurate, but leave the xPath text as it is! But please let me know, if you should encounter a textpart, which matches Thibault's description!

@pmsprenger: Please get rid of the subtype in your xPath, then I will gladly merge your pull request!

**Comment by pmsprenger** [comment]
My bad, I have redone the file. Should hook return "error" at this point?

**Comment by PonteIneptique** [comment]
Yes :) Hook can only test repositories written within the guidelines of Capitains ( http://capitains.github.io ). It means : 
- Text converted should be put in ./data/textgroupidentifier/workidentifier/urnlastpart.xml
- Text should be with their friendly friends called metadata :), ie `__cts__.xml`

**Comment by PonteIneptique** [comment]
Getting it much clearer : 

- Get the file in the directory `data/stoa0100a/stoa003`. 
- Name it stoa0100a.stoa003.temp-lat1.xml if you do not have any URN for now. 
- Change the urn in the file to match the file name, *ie* add `temp-lat1` or whatever at the end
- Add two `__cts__.xml` file using the template of CSEL and the metadata of catalog.perseus.org about `stoa0100a` and `stoa0100a.stoa003`

**Comment by annettegessner** [comment]
Since we don't have the correct URN for every work right now, we postponed this step till we have the confirmed URNs. By then, Matt will do the __cts__ files automatically and we can check for further errors in our files. So no hook for now. :-(

**Comment by PonteIneptique** [comment]
When Matt is back we should talk about it because I think it would not be harder to rename temp-lat1 than the current naming system :)

**Pull request merged**
