### PR TITLE
Fixing issue #1076 and #1402

### LINKED ISSUE #1402: PL83_25

### PR DESCRIPTION
**Pull request by pmsprenger**
This should be the right file now...

Close #1402 and #1076 when merging.

And close, discard #1403 when this has been successful.

### CODE REVIEW

**Comment by sonofmun** [comment]
Three things need to be corrected before this is merged:

    <idno type="filename">PL83_25_AP.xml</idno>

should be 

    <idno type="filename">tmp1428.tmp1428.opp-lat1.xml</idno>

and

    <cRefPattern n="p" matchPattern="(.+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@type='edition']/tei:p[@n='$1'])"/>

should be 

    <cRefPattern n="p" matchPattern="(.+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:p[@n='$1'])"/>

and

    <div type="edition" n="">

should be

    <div type="edition" n="urn:cts:latinLit:tmp1428.tmp1428.opp-lat1">

Please make these changes and push again.

**Comment by pmsprenger** [comment]
@sonofmun Should I also actually rename the file itself to tmp1428.tmp1428.opp-lat1.xml in this case?

**Comment by sonofmun** [comment]
@pmsprenger That already is the name of the file as far as I can see.

**Comment by pmsprenger** [comment]
My bad... Yes, it is.

About the second change: Why is `[@type='edition']` not needed anymore?

**Comment by sonofmun** [comment]
It makes the Hook tests faster if we don't have the type in the XPath. Therefore we should leave it out except where it is necessary. And here it isn't.

**Comment by pmsprenger** [comment]
Is there a general rule as to when it's not necessary? Can I just apply this to all the following pull requests or do I need to know something else about this?

**Comment by sonofmun** [comment]
Basically if there is only one `<div>` that is a direct child of `<body>`, the `<div type="edition">`, then you can leave it out. This will almost always be the case. Only if you had something like a prologue or table of contents, that was in its own, e.g.,  `<div type="commentary">` , would you need to specify the @type="edition" in the xpath. Otherwise it is clear which `<div>` is meant.  Does that make sense?

**Comment by pmsprenger** [comment]
Yes definitely. Thanks for clarifying!

**Comment by sonofmun** [comment]
Sorry @pmsprenger one more change:

    <refsDecl>

should be

    <refsDecl n="CTS">

Or at least that is how we have it in CSEL

**Comment by pmsprenger** [comment]
No problem. Changed it.

**Comment by pmsprenger** [comment]
File now passes hook.

**Pull request merged**
